"""cria modulo de formularios inteligentes

Revision ID: 12818a8eb5bc
Revises: 
Create Date: 2026-07-31 10:29:01.147505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12818a8eb5bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formularios_modelo',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('area_juridica_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['area_juridica_id'], ['areas_juridicas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('formularios_modelo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_formularios_modelo_area_juridica_id'), ['area_juridica_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_formularios_modelo_ativo'), ['ativo'], unique=False)
        batch_op.create_index(batch_op.f('ix_formularios_modelo_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_formularios_modelo_nome'), ['nome'], unique=False)

    op.create_table('formularios_caso',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('versao_modelo', sa.Integer(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('iniciado_em', sa.DateTime(), nullable=False),
    sa.Column('concluido_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('formulario_modelo_id', sa.String(length=36), nullable=False),
    sa.Column('caso_id', sa.String(length=36), nullable=False),
    sa.Column('cliente_id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['caso_id'], ['casos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['formulario_modelo_id'], ['formularios_modelo.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('formularios_caso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_formularios_caso_caso_id'), ['caso_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_formularios_caso_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_formularios_caso_formulario_modelo_id'), ['formulario_modelo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_formularios_caso_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_formularios_caso_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('perguntas_formulario',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('texto', sa.String(length=500), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('obrigatoria', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('placeholder', sa.String(length=255), nullable=True),
    sa.Column('opcoes_json', sa.Text(), nullable=True),
    sa.Column('valor_padrao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('formulario_modelo_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['formulario_modelo_id'], ['formularios_modelo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('formulario_modelo_id', 'codigo', name='uq_pergunta_formulario_codigo')
    )
    with op.batch_alter_table('perguntas_formulario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_perguntas_formulario_ativo'), ['ativo'], unique=False)
        batch_op.create_index(batch_op.f('ix_perguntas_formulario_codigo'), ['codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_perguntas_formulario_formulario_modelo_id'), ['formulario_modelo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_perguntas_formulario_ordem'), ['ordem'], unique=False)

    op.create_table('respostas_formulario',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('valor_texto', sa.Text(), nullable=True),
    sa.Column('valor_numero', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_data', sa.Date(), nullable=True),
    sa.Column('valor_hora', sa.Time(), nullable=True),
    sa.Column('valor_booleano', sa.Boolean(), nullable=True),
    sa.Column('valor_json', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('formulario_caso_id', sa.String(length=36), nullable=False),
    sa.Column('pergunta_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['formulario_caso_id'], ['formularios_caso.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pergunta_id'], ['perguntas_formulario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('formulario_caso_id', 'pergunta_id', name='uq_resposta_formulario_pergunta')
    )
    with op.batch_alter_table('respostas_formulario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_respostas_formulario_formulario_caso_id'), ['formulario_caso_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_respostas_formulario_pergunta_id'), ['pergunta_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respostas_formulario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_respostas_formulario_pergunta_id'))
        batch_op.drop_index(batch_op.f('ix_respostas_formulario_formulario_caso_id'))

    op.drop_table('respostas_formulario')
    with op.batch_alter_table('perguntas_formulario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_perguntas_formulario_ordem'))
        batch_op.drop_index(batch_op.f('ix_perguntas_formulario_formulario_modelo_id'))
        batch_op.drop_index(batch_op.f('ix_perguntas_formulario_codigo'))
        batch_op.drop_index(batch_op.f('ix_perguntas_formulario_ativo'))

    op.drop_table('perguntas_formulario')
    with op.batch_alter_table('formularios_caso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_formularios_caso_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_formularios_caso_status'))
        batch_op.drop_index(batch_op.f('ix_formularios_caso_formulario_modelo_id'))
        batch_op.drop_index(batch_op.f('ix_formularios_caso_cliente_id'))
        batch_op.drop_index(batch_op.f('ix_formularios_caso_caso_id'))

    op.drop_table('formularios_caso')
    with op.batch_alter_table('formularios_modelo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_formularios_modelo_nome'))
        batch_op.drop_index(batch_op.f('ix_formularios_modelo_codigo'))
        batch_op.drop_index(batch_op.f('ix_formularios_modelo_ativo'))
        batch_op.drop_index(batch_op.f('ix_formularios_modelo_area_juridica_id'))

    op.drop_table('formularios_modelo')
    # ### end Alembic commands ###
