"""adiciona etapas aos formularios

Revision ID: 803f36ec1d65
Revises: 12818a8eb5bc
Create Date: 2026-08-02 14:43:51.405501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '803f36ec1d65'
down_revision = '12818a8eb5bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perguntas_formulario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('etapa', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('ordem_etapa', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('grupo', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('icone', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('descricao_etapa', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_perguntas_formulario_etapa'), ['etapa'], unique=False)
        batch_op.create_index(batch_op.f('ix_perguntas_formulario_ordem_etapa'), ['ordem_etapa'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perguntas_formulario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_perguntas_formulario_ordem_etapa'))
        batch_op.drop_index(batch_op.f('ix_perguntas_formulario_etapa'))
        batch_op.drop_column('descricao_etapa')
        batch_op.drop_column('icone')
        batch_op.drop_column('grupo')
        batch_op.drop_column('ordem_etapa')
        batch_op.drop_column('etapa')

    # ### end Alembic commands ###
